### ISSUE TITLE
لطفا راهنمایی کن

### ISSUE THREAD

**Issue by arashlove2020** [xONEIROS/flashbots#2]
سلام وقت بخیر
من ولتم یه حالتی پیش اومده واسه شبکه پالیگان که متیک میزنم چند ثانیه بعد برداشت میشه
فقط هم متیک برداشت میشه در صورتی که روی شبکه پالیگان و شبکه های دیگه هم ارز دارم
الان بات روی وبت من گذاشته ؟ اگر اره و دسترسی به پرایوت کی من داره چرا فقط یه شبکه و یک ارز برداشت میشه!؟
راه حلی وجود داره؟

**Comment by xONEIROS** [comment]
ابتدا از این سایت ها چک کنید اگر اپرووالی دادید حذف کنید

[https://revoke.cash/](https://revoke.cash/)

[https://cointool.app/approve/matic](https://cointool.app/approve/matic)

اگر درست نشد ، احتمالا پراویت کیتون رفته .
باید والت عوض کنید.
